########## Testcase 0: Failed ##########
Expected Output: 
Cycle doesn't exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 13
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
Cycle doesn't exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 13
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 13
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 13
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 6: Failed ##########
Expected Output: 
Cycle doesn't exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

########## Testcase 7: Failed ##########
Expected Output: 
Cycle exists.

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at DirectedCycle.dfs(DirectedCycle.java:90)
	at Solution.main(Solution.java:36)
----------------------------------------

